name: Scan/Update Traan Stock

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install  Dependencies & Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev

      - name: Install Py Dependencies
        run: |
          pip install pytesseract pillow

      - name: Fetch  Discord Messages
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python3 src/scan_traan.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json data/current_stock.json
          git diff --staged --quiet || (git commit -m "AUTO: update traan stock cache" && git push)